# 1. The Numpy Package 

## 1.1 Numpy Array Basics

In [ ]:
import numpy as np #import numpy

In [ ]:
l = list(range(1,11)) #create a list
l

In [ ]:
my_array = np.array(l) #transform list into a numpy array (ndarray)
my_array

In [ ]:
type(my_array) 

In [ ]:
for i in my_array: # same as lists, ndarrays store multiple elements (is iterable) 
    print(i)

In [ ]:
l = [1, 2.5, "Dog", True] #lists can store different datatypes

In [ ]:
for i in l:
    print(type(i))

In [ ]:
a = np.array(l) #in ndarrays, all elements must have same datatype; numpy transforms automatically
a

In [ ]:
for i in a:
    print(type(i))

In [ ]:
b = np.array([1., "2", 3])
b

In [ ]:
type(b)

In [ ]:
b.dtype #can check single datatype of all elements with attribute .dtype

## 1.2 Numpy Array (element-wise operations / vectorization)

In [ ]:
import numpy as np

In [ ]:
np.arange(1,11) #create new ndarray from 1(incl.) to 11(excl.)

In [ ]:
np.arange(1,11,2) #only every second number is created 

In [ ]:
l = [1,2,3,4]
l

In [ ]:
l*2 #this is not an element-wise operation

In [ ]:
l1 = [] #element-wise operations with lists require a bunch of code
for i in l:
    l1.append(i*2)
l1

In [ ]:
a = np.arange(1,5) #create ndarray from 1 to 4 (both including)
a

In [ ]:
a * 2 

In [ ]:
a + 2 #addition works as well

In [ ]:
a**2 #all elements squared

In [ ]:
2**a #can serve as exponent as well

In [ ]:
np.sqrt(a) #square root of all elements

In [ ]:
np.exp(a) #exponentiation with e

In [ ]:
np.log(a) #natural logarithm

In [ ]:
a.sum() #sum of all elements (ndarray method)

In [ ]:
np.sum(a) #sum of all elements

In [ ]:
sum(a)

In [ ]:
a.size #number of elements in ndarray (ndarray attribute)

In [ ]:
len(a)

In [ ]:
b = np.array([-2, -1, -0.5, 0, 1, 2, 3.5])
b

In [ ]:
np.abs(b) #absolute values of all elements

In [ ]:
c = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
c

In [ ]:
np.ceil(c) #element-wise rounding up

In [ ]:
np.floor(c) #element-wise rounding down

In [ ]:
np.around([-3.23, -0.76, 1.44, 2.65, ], decimals = 0) #evenly round all elements to the given number of decimals.

## 1.3 Numpy Array (Indexing and Slicing)

In [ ]:
import numpy as np

In [ ]:
a = np.arange(1,11) #array from 1 to 10 (incl.)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a[0] #first element at index position 0 (zero-based indexing!)

1

In [ ]:
a[1] #second element (index position 1)

2

In [ ]:
a[-1] #last element

In [ ]:
list(enumerate(a)) #list of index,value tuples

[(0, 1),
 (1, 2),
 (2, 3),
 (3, 4),
 (4, 5),
 (5, 6),
 (6, 7),
 (7, 8),
 (8, 9),
 (9, 10)]

In [ ]:
a[2:6] #slicing from index position 2  till position 6  

array([3, 4, 5, 6])

In [ ]:
a[:] #all elements

In [ ]:
a[:5] #all elements until index position 5 

In [ ]:
a[6:] #all elements from index position 6  till the last element 

In [ ]:
a[::2] #every second element, starting from first element

In [ ]:
a[::3] #every third element, starting from first element

array([ 1,  4,  7, 10])

In [ ]:
a[2::3] #every third element, starting from third element (index position 2)

array([3, 6, 9])

In [ ]:
a[0] = 100 #ndarrays are mutable, changing first element to 100 
a

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [ ]:
a[-1] = 101 #changing last element to 101
a

In [ ]:
a[2:5] = 50 #in contrast to lists, ndarrays allow braodcasting, assigning one new value to multiple elements
a

In [ ]:
a[2:5] = [50, 51, 52] #assigning multiple new values to multiple elements
a

In [ ]:
a = np.arange(1,11) #creating new ndarray a
a

In [ ]:
b = a[2:8] # making a slice of ndarray a and assign new variable b, 
b
#try b =a[2:8].copy() afterwords

In [ ]:
b[0] = 100 #changing first element of ndarray b
b

In [ ]:
a #respective element of ndarray a has changed as well!!! 

In [ ]:
l = list(range(1,11)) #lists behave differently
l

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
m = l[2:8] #here a copy of the slice of l is created
m

[3, 4, 5, 6, 7, 8]

In [ ]:
m[0] = 100 #changing first element of slice m
m

In [ ]:
l #no effect on l

## 1.4 Numpy Array (Shape and multiple Dimensions)

In [ ]:
import numpy as np

In [ ]:
a = np.arange(1,13) #creating array from 1 to 12
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.shape #one-dimensional array, 12 elements in one dimension (vector)

(12,)

In [ ]:
a = a.reshape(2,6) #reshaping a: 2 rows / 6 columns

In [ ]:
a 

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [ ]:
a.shape # two-dimensional array: 2 rows / 6 columns (matrix)

(2, 6)

In [ ]:
a = a.reshape(6,2) # two-dimensional array: 6 rows / 2 columns
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [ ]:
a.shape

(6, 2)

In [ ]:
a + 100 #element-wise operations still work

array([[101, 102],
       [103, 104],
       [105, 106],
       [107, 108],
       [109, 110],
       [111, 112]])

In [ ]:
a*2

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16],
       [18, 20],
       [22, 24]])

In [ ]:
a = a.reshape(2,2,3) #creating a three-dimensional array
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
a.shape 

(2, 2, 3)

In [ ]:
b = np.arange(1,101).reshape(25,4) #creating 2-dim ndarray with one line of code
b

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [ 13,  14,  15,  16],
       [ 17,  18,  19,  20],
       [ 21,  22,  23,  24],
       [ 25,  26,  27,  28],
       [ 29,  30,  31,  32],
       [ 33,  34,  35,  36],
       [ 37,  38,  39,  40],
       [ 41,  42,  43,  44],
       [ 45,  46,  47,  48],
       [ 49,  50,  51,  52],
       [ 53,  54,  55,  56],
       [ 57,  58,  59,  60],
       [ 61,  62,  63,  64],
       [ 65,  66,  67,  68],
       [ 69,  70,  71,  72],
       [ 73,  74,  75,  76],
       [ 77,  78,  79,  80],
       [ 81,  82,  83,  84],
       [ 85,  86,  87,  88],
       [ 89,  90,  91,  92],
       [ 93,  94,  95,  96],
       [ 97,  98,  99, 100]])

## 1.5 Numpy Array (Indexing and Slicing multi-dimensional arrays)

In [ ]:
import numpy as np

In [ ]:
a = np.arange(1,13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
a = a.reshape(3,4) #creating matrix with 3 rows and 4 columns
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a[0] #first row (index position 0)

array([1, 2, 3, 4])

In [ ]:
a[1] #second row (index position 1)

In [ ]:
a[2] #third row (index position 2)

In [ ]:
a[-1] #last row (index position -1)

In [ ]:
a[1][1] #second row, second column

In [ ]:
a[1,1] #more convenient in one square bracket

In [ ]:
a[2,-1] #third row, last column

In [ ]:
a[:,0] #all rows, first column

In [ ]:
a[:,1] #all rows, second column

In [ ]:
a[:,-1] #all rows, last column

In [ ]:
a[:2,1:3] #first two rows, column two and three

array([[2, 3],
       [6, 7]])

In [ ]:
a

In [ ]:
a.T #Transpose: switching axes (attribute)

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [ ]:
a.transpose() #same (method)

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [ ]:
a

In [ ]:
a[:,-1] = a[:,-1] /4 #changing slice inplace

In [ ]:
a

array([[ 1,  2,  3,  1],
       [ 5,  6,  7,  2],
       [ 9, 10, 11,  3]])

In [ ]:
a = np.arange(1,13).reshape(3,4) #creating a 3x4 matrix
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a.sum() #sum over all elements in matrix

78

In [ ]:
a.sum(axis = 0) #sum of each column

array([15, 18, 21, 24])

In [ ]:
a.sum(axis = 1) #sum of each row

array([10, 26, 42])

In [ ]:
a.cumsum() #cumulative sum of all elements

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66, 78])

In [ ]:
a.cumsum(axis = 0) #cumulative sum for each column

array([[ 1,  2,  3,  4],
       [ 6,  8, 10, 12],
       [15, 18, 21, 24]])

In [ ]:
a.cumsum(axis = 1) #cumulative sum for each row

array([[ 1,  3,  6, 10],
       [ 5, 11, 18, 26],
       [ 9, 19, 30, 42]])

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a.prod() #product over all elements

479001600

In [ ]:
a.prod(axis = 0) #product over all elements in each column

array([ 45, 120, 231, 384])

In [ ]:
a.prod(axis = 1) #product over all elements in each row

array([   24,  1680, 11880])